<?php


namespace KamilKoscielniak\EloquentFilters\Tests;

use KamilKoscielniak\EloquentFilters\EloquentFiltersProvider;

class TestCase extends \Orchestra\Testbench\TestCase
{

    protected function getPackageProviders($app)
    {
        return [
            EloquentFiltersProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
//        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub

        $app['config']->set('database.default', 'testdb');
        $app['config']->set('database.connections.testdb', [
            'driver' => 'sqlite',
            'database' => ':memory:',
        ]);
    }

}
